# Learn YAML & Github Actions

name: Learn

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Hello Ejajul Ansari
        run: echo "Hello Ejajul Ansari"
      - name: Check NodeJS Version
        run: node -v
      - name: Create a readme.md file
        run: touch readme.md
      - name: Remove readme.md file
        run: rm -m readme.md
