name: "Ejajul Ansari is Learning Github Actions"

on:
  push:
    branches: main

jobs:
  nodejs-version-checkout:
    runs-on: ubuntu-latest
    
    steps:
      - name: NodeJS Version
        run: actions/setup-node@v3
        with:
          node-version: '22'
      - name: NodeJS Version
        run: node -v
  
  Build:
    runs-on: ubuntu-latest
    needs: nodejs-version-checkout
    
    steps:
      - name: Codebase Checkout
        run: actions/checkout@v4
      - name: Build Started
        run: echo "building..."

  Test:
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Codebase Checkout
        run: actions/checkout@v4
      - name: Test Started
        run: echo "Testing..."

  Deploying:
    runs-on: ubuntu-latest
    needs: Test
    
    steps:
      - name: Codebase Checkout
        run: actions/checkout@v4
      - name: Deploying Started
        run: echo "Deploying..."