# YAML GITHUB ACTIONS

name: Ejajul Ansari github actions

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: NodeJS Version
        run: echo node -v
      - name: Hello World
        run: echo Hello World
